/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net"
	"os"

	"github.com/go-redis/redis/v8"
	"google.golang.org/grpc"
	api "middleland.net/swaggerapi/petstore"
)

func main() {

	// Define command-line flags
	serverAddr := flag.String("serverAddr", "localhost", "HTTP server network address")
	serverPort := flag.Int("serverPort", 8090, "HTTP server network port")

	redisAddr := flag.String("redisAddr", "localhost:6379", "Redis address")
	redisPassword := flag.String("redisPassword", "", "Redis password")
	redisDB := flag.Int("redisDB", 0, "Redis DB")
	flag.Parse()

	// Create logger for writing information and error messages.
	infoLog := log.New(&api.ColoredWriter{W: os.Stdout, Color: api.ColorGreen}, "INFO\t", log.Ldate|log.Ltime)
	errLog := log.New(&api.ColoredWriter{W: os.Stderr, Color: api.ColorRed}, "ERROR\t", log.Ldate|log.Ltime|log.Lshortfile)

	// Create Redis client
	rdb := redis.NewClient(&redis.Options{
		Addr:     *redisAddr,
		Password: *redisPassword,
		DB:       *redisDB,
	})

	// Establish database connection (ping)
	ctx := context.Background() // global context
	_, err := rdb.Ping(ctx).Result()
	if err != nil {
		errLog.Fatal(err)
	}

	defer func() {
		if err := rdb.Close(); err != nil {
			errLog.Printf("Error closing redis: %v", err)
		}
	}()

	infoLog.Printf("Database connection established")
	app := api.NewLog(
		infoLog,
		errLog,
		&api.PetModel{
			Rdb: rdb,
		},
		&api.StoreModel{
			Rdb: rdb,
		},
		&api.UserModel{
			Rdb: rdb,
		},
	)

	// Initialize a new http.Server struct.
	serverURI := fmt.Sprintf("%s:%d", *serverAddr, *serverPort)
	infoLog.Printf("Starting server on %s", serverURI)

	// Start listening in serverPort
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", *serverPort))
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	// Create a new Grpc Server
	server := grpc.NewServer()
	api.RegisterSwaggerPetstoreServiceServer(server, app)

	// Start serve request
	log.Printf("server listening at %v", lis.Addr())
	if err := server.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
