/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/mongo"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Adds a new pet to the store
func (app *Application) AddPet(ctx context.Context, in *AddPetRequest) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	m := createPetEntity(in.GetBody())

	insertResult, err := app.pets.Insert(*m)
	if err != nil {
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "AddPet error: %s", err)
	}
	app.infoLog.Printf("New pet created: %s", insertResult.InsertedID)

	return out, nil
}

// Retrieves a pet by its numerical ID
func (app *Application) GetPetById(ctx context.Context, in *GetPetByIdRequest) (*Pet, error) {
	app.infoLog.Printf("Get pet by id=%d \n", in.PetId)

	model, err := app.pets.FindByID(in.PetId)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			app.infoLog.Println("Pet not found")
			return nil, status.Errorf(codes.NotFound, "Pet not found")
		}
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "GetPetById error: %s", err)
	}
	return createPetDTO(model), nil
}

// Deletes a pet from the store
func (app *Application) DeletePet(ctx context.Context, in *DeletePetRequest) (*emptypb.Empty, error) {
	app.infoLog.Printf("Delete pet by id=%d \n", in.PetId)

	deleteResult, err := app.pets.DeleteByID(in.PetId)
	if err != nil {
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "DeletePet error: %s", err)
	}

	app.infoLog.Printf("Deleted %d pet(s)", deleteResult.DeletedCount)
	return &emptypb.Empty{}, nil
}

// Returns pets filtered by status
func (app *Application) FindPetsByStatus(ctx context.Context, in *FindPetsByStatusRequest) (*FindPetsByStatusResponse, error) {
	app.infoLog.Printf("Endpoint Hit: FindPetsByStatus %s \n", in.Status)

	statusList := convertPetStatusList(in.Status)
	model, err := app.pets.FindByStatus(statusList)
	if err != nil {
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "FindPetsByStatus error: %s", err)
	}

	return &FindPetsByStatusResponse{Items: CreatePetListDTO(model)}, nil
}

// Returns pets filtered by tags
func (app *Application) FindPetsByTags(ctx context.Context, in *FindPetsByTagsRequest) (*FindPetsByTagsResponse, error) {
	app.infoLog.Printf("Endpoint Hit: FindPetsByTags %s \n", in.Tags)

	model, err := app.pets.FindBytags(in.Tags)
	if err != nil {
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "FindPetsByTags error: %s", err)
	}
	return &FindPetsByTagsResponse{Items: CreatePetListDTO(model)}, nil
}

// Updates an existing pet in the store
func (app *Application) UpdatePet(ctx context.Context, in *UpdatePetRequest) (*emptypb.Empty, error) {
	app.infoLog.Printf("Endpoint Hit: UpdatePet %v \n", in.GetBody())
	m := createPetEntity(in.GetBody())

	updateResult, err := app.pets.Update(*m)
	if err != nil {
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "UpdatePet error: %s", err)
	}

	app.infoLog.Printf("Pet updated, matched: %d, modified: %d", updateResult.MatchedCount, updateResult.ModifiedCount)
	return &emptypb.Empty{}, nil
}

func (app *Application) UpdatePetWithForm(ctx context.Context, in *UpdatePetWithFormRequest) (*emptypb.Empty, error) {
	app.infoLog.Printf("UpdatePetWithForm: id=%d, name=%s, status=%s", in.PetId, in.Name, in.Status)

	// Find Pet by id
	petEntity, err := app.pets.FindByID(in.PetId)
	app.infoLog.Printf("Endpoint Hit: UpdatePetWithForm %s \n", petEntity)

	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			app.infoLog.Printf("Pet not found: %d", in.PetId)
			return nil, status.Errorf(codes.NotFound, "Pet not found: %d", in.PetId)
		}
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "Error finding pet: %v", err)
	}

	// Update fields if provided
	if in.Name != "" {
		petEntity.Name = in.Name
	}
	if in.Status != "" {
		petEntity.Status = in.Status
	}

	// Update in DB
	_, err = app.pets.Update(*petEntity)
	if err != nil {
		app.serverError(err)
		return nil, status.Errorf(codes.Internal, "Error updating pet: %v", err)
	}

	return &emptypb.Empty{}, nil
}

func (app *Application) UploadFile(ctx context.Context, in *UploadFileRequest) (*ApiResponse, error) {
	app.infoLog.Printf("UploadFile:: id=%d, metadata=%s\n", in.PetId, in.AdditionalMetadata)
	// Basic implementation: just acknowledge receipt if data is present
	if in.File == "" {
		app.infoLog.Printf("UploadFile:: file data is missing")
		return nil, status.Errorf(codes.InvalidArgument, "file data is missing")
	}

	return &ApiResponse{
		Code:    200,
		Type:    "unknown",
		Message: fmt.Sprintf("File uploaded for pet %d with metadata %s", in.PetId, in.AdditionalMetadata),
	}, nil
}
