/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"context"
	"errors"
	"fmt"

	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// CreateUser creates a new user.
func (s *Application) CreateUser(ctx context.Context, in *CreateUserRequest) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: CreateUser %s", in.Body.Username)
	if in.Body == nil {
		return nil, status.Errorf(codes.InvalidArgument, "request body is empty")
	}

	userEntity := UserEntity{
		Id:         in.Body.Id,
		Username:   in.Body.Username,
		FirstName:  in.Body.FirstName,
		LastName:   in.Body.LastName,
		Email:      in.Body.Email,
		Password:   in.Body.Password,
		Phone:      in.Body.Phone,
		UserStatus: in.Body.UserStatus,
	}

	_, err := s.users.Insert(ctx, userEntity)
	if err != nil {
		s.serverError(err)
		return nil, status.Errorf(codes.Internal, "failed to create user: %v", err)
	}

	return &emptypb.Empty{}, nil
}

// CreateUsersWithArrayInput batch creates users from an array input.
func (s *Application) CreateUsersWithArrayInput(ctx context.Context, in *CreateUsersWithArrayInputRequest) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: CreateUsersWithArrayInput")
	for _, user := range in.Body {
		userEntity := UserEntity{
			Id:         user.Id,
			Username:   user.Username,
			FirstName:  user.FirstName,
			LastName:   user.LastName,
			Email:      user.Email,
			Password:   user.Password,
			Phone:      user.Phone,
			UserStatus: user.UserStatus,
		}
		_, err := s.users.Insert(ctx, userEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "failed to create user %s: %v", user.Username, err)
		}
	}
	return &emptypb.Empty{}, nil
}

// CreateUsersWithListInput batch creates users from a list input.
func (s *Application) CreateUsersWithListInput(ctx context.Context, in *CreateUsersWithListInputRequest) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: CreateUsersWithListInput")
	for _, user := range in.Body {
		userEntity := UserEntity{
			Id:         user.Id,
			Username:   user.Username,
			FirstName:  user.FirstName,
			LastName:   user.LastName,
			Email:      user.Email,
			Password:   user.Password,
			Phone:      user.Phone,
			UserStatus: user.UserStatus,
		}
		_, err := s.users.Insert(ctx, userEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "failed to create user %s: %v", user.Username, err)
		}
	}
	return &emptypb.Empty{}, nil
}

// DeleteUser deletes a user by username.
func (s *Application) DeleteUser(ctx context.Context, in *DeleteUserRequest) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: DeleteUser %s", in.Username)
	_, err := s.users.Delete(ctx, in.Username)
	if err != nil {
		s.serverError(err)
		return nil, status.Errorf(codes.Internal, "failed to delete user: %v", err)
	}
	return &emptypb.Empty{}, nil
}

// GetUserByName fetches a user by their username.
func (s *Application) GetUserByName(ctx context.Context, in *GetUserByNameRequest) (*User, error) {
	s.infoLog.Printf("Endpoint Hit: GetUserByName %s", in.Username)
	userEntity, err := s.users.FindByName(ctx, in.Username)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil, status.Errorf(codes.NotFound, "user not found: %s", in.Username)
		}
		return nil, status.Errorf(codes.NotFound, "user not found: %v", err)
	}

	return &User{
		Id:         userEntity.Id,
		Username:   userEntity.Username,
		FirstName:  userEntity.FirstName,
		LastName:   userEntity.LastName,
		Email:      userEntity.Email,
		Password:   userEntity.Password,
		Phone:      userEntity.Phone,
		UserStatus: userEntity.UserStatus,
	}, nil
}

// LoginUser authenticates a user and starts a session.
func (s *Application) LoginUser(ctx context.Context, in *LoginUserRequest) (*ApiResponse, error) {
	s.infoLog.Printf("Endpoint Hit: LoginUser %s", in.Username)
	user, err := s.users.FindByName(ctx, in.Username)
	if err != nil || user == nil || user.Password != in.Password {
		return nil, status.Errorf(codes.Unauthenticated, "invalid username or password")
	}

	sessionId := fmt.Sprintf("logged-in-session-%s", user.Username)
	return &ApiResponse{
		Code:    200,
		Type:    "unknown",
		Message: "logged in user session: " + sessionId,
	}, nil
}

// LogoutUser logs out the current user session.
func (s *Application) LogoutUser(ctx context.Context, in *emptypb.Empty) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: LogoutUser")
	return &emptypb.Empty{}, nil
}

// UpdateUser updates an existing user's information.
func (s *Application) UpdateUser(ctx context.Context, in *UpdateUserRequest) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: UpdateUser %s", in.Username)
	if in.Body == nil {
		return nil, status.Errorf(codes.InvalidArgument, "request body is empty")
	}

	userEntity := UserEntity{
		Id:         in.Body.Id,
		Username:   in.Body.Username,
		FirstName:  in.Body.FirstName,
		LastName:   in.Body.LastName,
		Email:      in.Body.Email,
		Password:   in.Body.Password,
		Phone:      in.Body.Phone,
		UserStatus: in.Body.UserStatus,
	}

	_, err := s.users.Update(ctx, userEntity)
	if err != nil {
		s.serverError(err)
		return nil, status.Errorf(codes.Internal, "failed to update user: %v", err)
	}

	return &emptypb.Empty{}, nil
}
