/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"context"
	"fmt"

	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func (s *Application) DeleteOrder(context context.Context, in *DeleteOrderRequest) (*emptypb.Empty, error) {

	fmt.Println("DeleteOrder:: create a new user")
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}

func (s *Application) GetInventory(context context.Context, in *emptypb.Empty) (*GetInventoryResponse, error) {

	fmt.Println("GetInventory:: get inventory")
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}

func (s *Application) GetOrderById(context context.Context, in *GetOrderByIdRequest) (*Order, error) {

	fmt.Println("GetOrderById:: get order by id")
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderById not implemented")
}

func (s *Application) PlaceOrder(context context.Context, in *PlaceOrderRequest) (*Order, error) {

	fmt.Println("PlaceOrder:: place a new order")
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
