/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"context"
	"errors"

	"go.mongodb.org/mongo-driver/mongo"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Deletes an order by its numerical ID
func (s *Application) DeleteOrder(ctx context.Context, in *DeleteOrderRequest) (*emptypb.Empty, error) {
	s.infoLog.Printf("Endpoint Hit: DeleteOrder %d", in.OrderId)
	_, err := s.stores.DeleteByID(ctx, in.OrderId)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "failed to delete order: %v", err)
	}
	return &emptypb.Empty{}, nil
}

// Returns pet inventories by status
func (s *Application) GetInventory(ctx context.Context, in *emptypb.Empty) (*GetInventoryResponse, error) {
	s.infoLog.Printf("Endpoint Hit: GetInventory")
	inventory, err := s.stores.GetInventory(ctx, s.pets.C)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "failed to get inventory: %v", err)
	}

	items := []*MapInventory{}
	for k, v := range inventory {
		items = append(items, &MapInventory{Name: k, Value: int64(v)})
	}
	return &GetInventoryResponse{Items: items}, nil
}

// Retrieves an order by its numerical ID
func (s *Application) GetOrderById(ctx context.Context, in *GetOrderByIdRequest) (*Order, error) {
	s.infoLog.Printf("Endpoint Hit: GetOrderById %d", in.OrderId)
	orderEntity, err := s.stores.FindByID(ctx, in.OrderId)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, status.Errorf(codes.NotFound, "order not found")
		}
		return nil, status.Errorf(codes.Internal, "failed to get order: %v", err)
	}
	return createOrderDTO(orderEntity), nil
}

// Places a new order for a pet
func (s *Application) PlaceOrder(ctx context.Context, in *PlaceOrderRequest) (*Order, error) {
	s.infoLog.Printf("Endpoint Hit: PlaceOrder %v", in.Body)
	if in.Body == nil {
		return nil, status.Errorf(codes.InvalidArgument, "order body is required")
	}

	orderEntity := createOrderEntity(in.Body)
	_, err := s.stores.Insert(ctx, *orderEntity)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "failed to place order: %v", err)
	}
	return createOrderDTO(orderEntity), nil
}
