/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"io"
	"log"
)

const (
	ColorReset  = "\033[0m"
	ColorRed    = "\033[31m"
	ColorGreen  = "\033[32m"
	ColorYellow = "\033[33m"
	ColorBlue   = "\033[34m"
	ColorPurple = "\033[35m"
	ColorCyan   = "\033[36m"
	ColorGray   = "\033[37m"
)

// ColoredWriter wraps an io.Writer and adds color to the output
type ColoredWriter struct {
	W     io.Writer
	Color string
}

func (cw *ColoredWriter) Write(p []byte) (n int, err error) {
	cw.W.Write([]byte(cw.Color))
	n, err = cw.W.Write(p)
	cw.W.Write([]byte(ColorReset))
	return
}

func Logger(level string, method string, data string) {
	var colorStart string
	var colorReset = ColorReset

	switch level {
	case "INFO":
		colorStart = ColorGreen
	case "DEBUG":
		colorStart = ColorBlue
	case "ERROR":
		colorStart = ColorRed
	default:
		colorStart = ColorReset
	}

	// Use standard log but include color codes in the message
	log.Printf(
		"%s[%s] %s %s%s",
		colorStart,
		level,
		method,
		data,
		colorReset)
}
