/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

// Map string status to PetStatus enum
var (
	PetStatusEnum = map[string]Pet_PetStatus{
		"STATUS_AVAILABLE": Pet_STATUS_AVAILABLE,
		"STATUS_PENDING":   Pet_STATUS_PENDING,
		"STATUS_SOLD":      Pet_STATUS_SOLD,
	}
)

// Converts Pet DTO to PetEntity
func createPetEntity(in *Pet) *PetEntity {

	tags := []TagEntity{}
	for _, item := range in.Tags {
		tags = append(tags, TagEntity{Id: item.Id, Name: item.Name})
	}

	photoUrls := []string{}
	photoUrls = append(photoUrls, in.PhotoUrls...)

	var categoryEntity *CategoryEntity
	if in.Category != nil {
		categoryEntity = &CategoryEntity{Id: in.Category.Id, Name: in.Category.Name}
	}

	result := &PetEntity{Id: in.Id, Category: categoryEntity,
		Name: in.Name, Tags: tags, Status: in.Status.String(), PhotoUrls: photoUrls}

	return result
}

// Converts PetEntity to Pet DTO
func createPetDTO(in *PetEntity) *Pet {

	tags := []*Tag{}
	for _, item := range in.Tags {
		tags = append(tags, &Tag{Id: item.Id, Name: item.Name})
	}

	photoUrls := []string{}
	photoUrls = append(photoUrls, in.PhotoUrls...)

	var category *Category
	if in.Category != nil {
		category = &Category{Id: in.Category.Id, Name: in.Category.Name}
	}

	statusDTO := PetStatusEnum[in.Status]
	result := &Pet{Id: in.Id, Category: category,
		Name: in.Name, Tags: tags, Status: statusDTO, PhotoUrls: photoUrls}

	return result
}

// Converts status enum list to string list
func convertPetStatusList(status []FindPetsByStatusRequest_Status) []string {

	result := []string{}
	for _, item := range status {
		result = append(result, Pet_PetStatus(item).String())
	}

	return result
}

// Converts list of PetEntities to list of Pet DTOs
func CreatePetListDTO(pets []PetEntity) []*Pet {

	result := []*Pet{}
	for _, item := range pets {
		result = append(result, createPetDTO(&item))
	}

	return result
}
