// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: protobuffer/swaggerpetstore/petstore.proto

package petstore

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindPetsByStatusRequest_Status int32

const (
	FindPetsByStatusRequest_STATUS_AVAILABLE FindPetsByStatusRequest_Status = 0
	FindPetsByStatusRequest_STATUS_PENDING   FindPetsByStatusRequest_Status = 1
	FindPetsByStatusRequest_STATUS_SOLD      FindPetsByStatusRequest_Status = 2
)

// Enum value maps for FindPetsByStatusRequest_Status.
var (
	FindPetsByStatusRequest_Status_name = map[int32]string{
		0: "STATUS_AVAILABLE",
		1: "STATUS_PENDING",
		2: "STATUS_SOLD",
	}
	FindPetsByStatusRequest_Status_value = map[string]int32{
		"STATUS_AVAILABLE": 0,
		"STATUS_PENDING":   1,
		"STATUS_SOLD":      2,
	}
)

func (x FindPetsByStatusRequest_Status) Enum() *FindPetsByStatusRequest_Status {
	p := new(FindPetsByStatusRequest_Status)
	*p = x
	return p
}

func (x FindPetsByStatusRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindPetsByStatusRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuffer_swaggerpetstore_petstore_proto_enumTypes[0].Descriptor()
}

func (FindPetsByStatusRequest_Status) Type() protoreflect.EnumType {
	return &file_protobuffer_swaggerpetstore_petstore_proto_enumTypes[0]
}

func (x FindPetsByStatusRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindPetsByStatusRequest_Status.Descriptor instead.
func (FindPetsByStatusRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{4, 0}
}

type Order_OrderStatus int32

const (
	Order_ORDER_STATUS_PLACED    Order_OrderStatus = 0
	Order_ORDER_STATUS_APPROVED  Order_OrderStatus = 1
	Order_ORDER_STATUS_DELIVERED Order_OrderStatus = 2
)

// Enum value maps for Order_OrderStatus.
var (
	Order_OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_PLACED",
		1: "ORDER_STATUS_APPROVED",
		2: "ORDER_STATUS_DELIVERED",
	}
	Order_OrderStatus_value = map[string]int32{
		"ORDER_STATUS_PLACED":    0,
		"ORDER_STATUS_APPROVED":  1,
		"ORDER_STATUS_DELIVERED": 2,
	}
)

func (x Order_OrderStatus) Enum() *Order_OrderStatus {
	p := new(Order_OrderStatus)
	*p = x
	return p
}

func (x Order_OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order_OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuffer_swaggerpetstore_petstore_proto_enumTypes[1].Descriptor()
}

func (Order_OrderStatus) Type() protoreflect.EnumType {
	return &file_protobuffer_swaggerpetstore_petstore_proto_enumTypes[1]
}

func (x Order_OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order_OrderStatus.Descriptor instead.
func (Order_OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{9, 0}
}

type Pet_PetStatus int32

const (
	Pet_STATUS_AVAILABLE Pet_PetStatus = 0
	Pet_STATUS_PENDING   Pet_PetStatus = 1
	Pet_STATUS_SOLD      Pet_PetStatus = 2
)

// Enum value maps for Pet_PetStatus.
var (
	Pet_PetStatus_name = map[int32]string{
		0: "STATUS_AVAILABLE",
		1: "STATUS_PENDING",
		2: "STATUS_SOLD",
	}
	Pet_PetStatus_value = map[string]int32{
		"STATUS_AVAILABLE": 0,
		"STATUS_PENDING":   1,
		"STATUS_SOLD":      2,
	}
)

func (x Pet_PetStatus) Enum() *Pet_PetStatus {
	p := new(Pet_PetStatus)
	*p = x
	return p
}

func (x Pet_PetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pet_PetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuffer_swaggerpetstore_petstore_proto_enumTypes[2].Descriptor()
}

func (Pet_PetStatus) Type() protoreflect.EnumType {
	return &file_protobuffer_swaggerpetstore_petstore_proto_enumTypes[2]
}

func (x Pet_PetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pet_PetStatus.Descriptor instead.
func (Pet_PetStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{15, 0}
}

type AddPetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pet object that needs to be added to the store
	Body          *Pet `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPetRequest) Reset() {
	*x = AddPetRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetRequest) ProtoMessage() {}

func (x *AddPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetRequest.ProtoReflect.Descriptor instead.
func (*AddPetRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{0}
}

func (x *AddPetRequest) GetBody() *Pet {
	if x != nil {
		return x.Body
	}
	return nil
}

type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePetRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ApiKey string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Pet id to delete
	PetId         int64 `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePetRequest) Reset() {
	*x = DeletePetRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetRequest) ProtoMessage() {}

func (x *DeletePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetRequest.ProtoReflect.Descriptor instead.
func (*DeletePetRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePetRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeletePetRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

type FindPetsByStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status values that need to be considered for filter
	Status        []FindPetsByStatusRequest_Status `protobuf:"varint,1,rep,packed,name=status,proto3,enum=petstore.FindPetsByStatusRequest_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPetsByStatusRequest) Reset() {
	*x = FindPetsByStatusRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPetsByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPetsByStatusRequest) ProtoMessage() {}

func (x *FindPetsByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPetsByStatusRequest.ProtoReflect.Descriptor instead.
func (*FindPetsByStatusRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{4}
}

func (x *FindPetsByStatusRequest) GetStatus() []FindPetsByStatusRequest_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type FindPetsByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Pet                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPetsByStatusResponse) Reset() {
	*x = FindPetsByStatusResponse{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPetsByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPetsByStatusResponse) ProtoMessage() {}

func (x *FindPetsByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPetsByStatusResponse.ProtoReflect.Descriptor instead.
func (*FindPetsByStatusResponse) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{5}
}

func (x *FindPetsByStatusResponse) GetItems() []*Pet {
	if x != nil {
		return x.Items
	}
	return nil
}

type FindPetsByTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tags to filter by
	Tags          []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPetsByTagsRequest) Reset() {
	*x = FindPetsByTagsRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPetsByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPetsByTagsRequest) ProtoMessage() {}

func (x *FindPetsByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPetsByTagsRequest.ProtoReflect.Descriptor instead.
func (*FindPetsByTagsRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{6}
}

func (x *FindPetsByTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type FindPetsByTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Pet                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPetsByTagsResponse) Reset() {
	*x = FindPetsByTagsResponse{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPetsByTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPetsByTagsResponse) ProtoMessage() {}

func (x *FindPetsByTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPetsByTagsResponse.ProtoReflect.Descriptor instead.
func (*FindPetsByTagsResponse) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{7}
}

func (x *FindPetsByTagsResponse) GetItems() []*Pet {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPetByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of pet to return
	PetId         int64 `protobuf:"varint,1,opt,name=petId,proto3" json:"petId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetByIdRequest) Reset() {
	*x = GetPetByIdRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetByIdRequest) ProtoMessage() {}

func (x *GetPetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPetByIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{8}
}

func (x *GetPetByIdRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

type Order struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Complete bool                   `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	Id       int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PetId    int64                  `protobuf:"varint,3,opt,name=petId,proto3" json:"petId,omitempty"`
	Quantity int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ShipDate string                 `protobuf:"bytes,5,opt,name=shipDate,proto3" json:"shipDate,omitempty"`
	// Order Status
	Status        Order_OrderStatus `protobuf:"varint,6,opt,name=status,proto3,enum=petstore.Order_OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{9}
}

func (x *Order) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetShipDate() string {
	if x != nil {
		return x.ShipDate
	}
	return ""
}

func (x *Order) GetStatus() Order_OrderStatus {
	if x != nil {
		return x.Status
	}
	return Order_ORDER_STATUS_PLACED
}

type DeleteOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the order that needs to be deleted
	OrderId       int64 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MapInventory        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{11}
}

func (x *GetInventoryResponse) GetItems() []*MapInventory {
	if x != nil {
		return x.Items
	}
	return nil
}

type MapInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInventory) Reset() {
	*x = MapInventory{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInventory) ProtoMessage() {}

func (x *MapInventory) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInventory.ProtoReflect.Descriptor instead.
func (*MapInventory) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{12}
}

func (x *MapInventory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapInventory) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetOrderByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of pet that needs to be fetched
	OrderId       int64 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdRequest) Reset() {
	*x = GetOrderByIdRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdRequest) ProtoMessage() {}

func (x *GetOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderByIdRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PlaceOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order placed for purchasing the pet
	Body          *Order `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{14}
}

func (x *PlaceOrderRequest) GetBody() *Order {
	if x != nil {
		return x.Body
	}
	return nil
}

type Pet struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Category  *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Id        int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrls []string               `protobuf:"bytes,4,rep,name=photoUrls,proto3" json:"photoUrls,omitempty"`
	// pet status in the store
	Status        Pet_PetStatus `protobuf:"varint,5,opt,name=status,proto3,enum=petstore.Pet_PetStatus" json:"status,omitempty"`
	Tags          []*Tag        `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{15}
}

func (x *Pet) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Pet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *Pet) GetStatus() Pet_PetStatus {
	if x != nil {
		return x.Status
	}
	return Pet_STATUS_AVAILABLE
}

func (x *Pet) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{16}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatePetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pet object that needs to be added to the store
	Body          *Pet `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePetRequest) GetBody() *Pet {
	if x != nil {
		return x.Body
	}
	return nil
}

type UpdatePetWithFormRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated name of the pet
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID of pet that needs to be updated
	PetId int64 `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`
	// Updated status of the pet
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetWithFormRequest) Reset() {
	*x = UpdatePetWithFormRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetWithFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetWithFormRequest) ProtoMessage() {}

func (x *UpdatePetWithFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetWithFormRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetWithFormRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{18}
}

func (x *UpdatePetWithFormRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePetWithFormRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *UpdatePetWithFormRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Additional data to pass to server
	AdditionalMetadata string `protobuf:"bytes,1,opt,name=additionalMetadata,proto3" json:"additionalMetadata,omitempty"`
	// file to upload
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// ID of pet to update
	PetId         int64 `protobuf:"varint,3,opt,name=petId,proto3" json:"petId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{19}
}

func (x *UploadFileRequest) GetAdditionalMetadata() string {
	if x != nil {
		return x.AdditionalMetadata
	}
	return ""
}

func (x *UploadFileRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *UploadFileRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	UserStatus    int32                  `protobuf:"varint,8,opt,name=userStatus,proto3" json:"userStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{20}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetUserStatus() int32 {
	if x != nil {
		return x.UserStatus
	}
	return 0
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created user object
	Body          *User `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{21}
}

func (x *CreateUserRequest) GetBody() *User {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateUsersWithArrayInputRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of user object
	Body          []*User `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsersWithArrayInputRequest) Reset() {
	*x = CreateUsersWithArrayInputRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsersWithArrayInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsersWithArrayInputRequest) ProtoMessage() {}

func (x *CreateUsersWithArrayInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsersWithArrayInputRequest.ProtoReflect.Descriptor instead.
func (*CreateUsersWithArrayInputRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{22}
}

func (x *CreateUsersWithArrayInputRequest) GetBody() []*User {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateUsersWithListInputRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of user object
	Body          []*User `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsersWithListInputRequest) Reset() {
	*x = CreateUsersWithListInputRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsersWithListInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsersWithListInputRequest) ProtoMessage() {}

func (x *CreateUsersWithListInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsersWithListInputRequest.ProtoReflect.Descriptor instead.
func (*CreateUsersWithListInputRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{23}
}

func (x *CreateUsersWithListInputRequest) GetBody() []*User {
	if x != nil {
		return x.Body
	}
	return nil
}

type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name that needs to be deleted
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name that needs to be fetched. Use user1 for testing.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByNameRequest) Reset() {
	*x = GetUserByNameRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByNameRequest) ProtoMessage() {}

func (x *GetUserByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByNameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByNameRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserByNameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LoginUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The password for login in clear text
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// The user name for login
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{26}
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user object
	Body *User `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// name that need to be updated
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_swaggerpetstore_petstore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateUserRequest) GetBody() *User {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_protobuffer_swaggerpetstore_petstore_proto protoreflect.FileDescriptor

const file_protobuffer_swaggerpetstore_petstore_proto_rawDesc = "" +
	"\n" +
	"*protobuffer/swaggerpetstore/petstore.proto\x12\bpetstore\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\rAddPetRequest\x12!\n" +
	"\x04body\x18\x01 \x01(\v2\r.petstore.PetR\x04body\"O\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"A\n" +
	"\x10DeletePetRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05petId\x18\x02 \x01(\x03R\x05petId\"\xa0\x01\n" +
	"\x17FindPetsByStatusRequest\x12@\n" +
	"\x06status\x18\x01 \x03(\x0e2(.petstore.FindPetsByStatusRequest.StatusR\x06status\"C\n" +
	"\x06Status\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x0f\n" +
	"\vSTATUS_SOLD\x10\x02\"?\n" +
	"\x18FindPetsByStatusResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.petstore.PetR\x05items\"+\n" +
	"\x15FindPetsByTagsRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"=\n" +
	"\x16FindPetsByTagsResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.petstore.PetR\x05items\")\n" +
	"\x11GetPetByIdRequest\x12\x14\n" +
	"\x05petId\x18\x01 \x01(\x03R\x05petId\"\x95\x02\n" +
	"\x05Order\x12\x1a\n" +
	"\bcomplete\x18\x01 \x01(\bR\bcomplete\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x14\n" +
	"\x05petId\x18\x03 \x01(\x03R\x05petId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bshipDate\x18\x05 \x01(\tR\bshipDate\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.petstore.Order.OrderStatusR\x06status\"]\n" +
	"\vOrderStatus\x12\x17\n" +
	"\x13ORDER_STATUS_PLACED\x10\x00\x12\x19\n" +
	"\x15ORDER_STATUS_APPROVED\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x02\".\n" +
	"\x12DeleteOrderRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\"D\n" +
	"\x14GetInventoryResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.petstore.MapInventoryR\x05items\"8\n" +
	"\fMapInventory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"/\n" +
	"\x13GetOrderByIdRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\"8\n" +
	"\x11PlaceOrderRequest\x12#\n" +
	"\x04body\x18\x01 \x01(\v2\x0f.petstore.OrderR\x04body\"\x93\x02\n" +
	"\x03Pet\x12.\n" +
	"\bcategory\x18\x01 \x01(\v2\x12.petstore.CategoryR\bcategory\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tphotoUrls\x18\x04 \x03(\tR\tphotoUrls\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.petstore.Pet.PetStatusR\x06status\x12!\n" +
	"\x04tags\x18\x06 \x03(\v2\r.petstore.TagR\x04tags\"F\n" +
	"\tPetStatus\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x0f\n" +
	"\vSTATUS_SOLD\x10\x02\")\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x10UpdatePetRequest\x12!\n" +
	"\x04body\x18\x01 \x01(\v2\r.petstore.PetR\x04body\"\\\n" +
	"\x18UpdatePetWithFormRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05petId\x18\x02 \x01(\x03R\x05petId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"m\n" +
	"\x11UploadFileRequest\x12.\n" +
	"\x12additionalMetadata\x18\x01 \x01(\tR\x12additionalMetadata\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x14\n" +
	"\x05petId\x18\x03 \x01(\x03R\x05petId\"\xd4\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1e\n" +
	"\n" +
	"userStatus\x18\b \x01(\x05R\n" +
	"userStatus\"7\n" +
	"\x11CreateUserRequest\x12\"\n" +
	"\x04body\x18\x01 \x01(\v2\x0e.petstore.UserR\x04body\"F\n" +
	" CreateUsersWithArrayInputRequest\x12\"\n" +
	"\x04body\x18\x01 \x03(\v2\x0e.petstore.UserR\x04body\"E\n" +
	"\x1fCreateUsersWithListInputRequest\x12\"\n" +
	"\x04body\x18\x01 \x03(\v2\x0e.petstore.UserR\x04body\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"2\n" +
	"\x14GetUserByNameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"J\n" +
	"\x10LoginUserRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"S\n" +
	"\x11UpdateUserRequest\x12\"\n" +
	"\x04body\x18\x01 \x01(\v2\x0e.petstore.UserR\x04body\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername2\xcb\v\n" +
	"\x16SwaggerPetstoreService\x12;\n" +
	"\x06AddPet\x12\x17.petstore.AddPetRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\vDeleteOrder\x12\x1c.petstore.DeleteOrderRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\tDeletePet\x12\x1a.petstore.DeletePetRequest\x1a\x16.google.protobuf.Empty\"\x00\x12[\n" +
	"\x10FindPetsByStatus\x12!.petstore.FindPetsByStatusRequest\x1a\".petstore.FindPetsByStatusResponse\"\x00\x12U\n" +
	"\x0eFindPetsByTags\x12\x1f.petstore.FindPetsByTagsRequest\x1a .petstore.FindPetsByTagsResponse\"\x00\x12H\n" +
	"\fGetInventory\x12\x16.google.protobuf.Empty\x1a\x1e.petstore.GetInventoryResponse\"\x00\x12@\n" +
	"\fGetOrderById\x12\x1d.petstore.GetOrderByIdRequest\x1a\x0f.petstore.Order\"\x00\x12:\n" +
	"\n" +
	"GetPetById\x12\x1b.petstore.GetPetByIdRequest\x1a\r.petstore.Pet\"\x00\x12A\n" +
	"\tUpdatePet\x12\x1a.petstore.UpdatePetRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Q\n" +
	"\x11UpdatePetWithForm\x12\".petstore.UpdatePetWithFormRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\n" +
	"UploadFile\x12\x1b.petstore.UploadFileRequest\x1a\x15.petstore.ApiResponse\"\x00\x12C\n" +
	"\n" +
	"CreateUser\x12\x1b.petstore.CreateUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12a\n" +
	"\x19CreateUsersWithArrayInput\x12*.petstore.CreateUsersWithArrayInputRequest\x1a\x16.google.protobuf.Empty\"\x00\x12_\n" +
	"\x18CreateUsersWithListInput\x12).petstore.CreateUsersWithListInputRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\n" +
	"DeleteUser\x12\x1b.petstore.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\rGetUserByName\x12\x1e.petstore.GetUserByNameRequest\x1a\x0e.petstore.User\"\x00\x12@\n" +
	"\tLoginUser\x12\x1a.petstore.LoginUserRequest\x1a\x15.petstore.ApiResponse\"\x00\x12>\n" +
	"\n" +
	"LogoutUser\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\n" +
	"PlaceOrder\x12\x1b.petstore.PlaceOrderRequest\x1a\x0f.petstore.Order\"\x00\x12C\n" +
	"\n" +
	"UpdateUser\x12\x1b.petstore.UpdateUserRequest\x1a\x16.google.protobuf.Empty\"\x00B$Z\"middleland.net/swaggerapi/petstoreb\x06proto3"

var (
	file_protobuffer_swaggerpetstore_petstore_proto_rawDescOnce sync.Once
	file_protobuffer_swaggerpetstore_petstore_proto_rawDescData []byte
)

func file_protobuffer_swaggerpetstore_petstore_proto_rawDescGZIP() []byte {
	file_protobuffer_swaggerpetstore_petstore_proto_rawDescOnce.Do(func() {
		file_protobuffer_swaggerpetstore_petstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuffer_swaggerpetstore_petstore_proto_rawDesc), len(file_protobuffer_swaggerpetstore_petstore_proto_rawDesc)))
	})
	return file_protobuffer_swaggerpetstore_petstore_proto_rawDescData
}

var file_protobuffer_swaggerpetstore_petstore_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuffer_swaggerpetstore_petstore_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_protobuffer_swaggerpetstore_petstore_proto_goTypes = []any{
	(FindPetsByStatusRequest_Status)(0),      // 0: petstore.FindPetsByStatusRequest.Status
	(Order_OrderStatus)(0),                   // 1: petstore.Order.OrderStatus
	(Pet_PetStatus)(0),                       // 2: petstore.Pet.PetStatus
	(*AddPetRequest)(nil),                    // 3: petstore.AddPetRequest
	(*ApiResponse)(nil),                      // 4: petstore.ApiResponse
	(*Category)(nil),                         // 5: petstore.Category
	(*DeletePetRequest)(nil),                 // 6: petstore.DeletePetRequest
	(*FindPetsByStatusRequest)(nil),          // 7: petstore.FindPetsByStatusRequest
	(*FindPetsByStatusResponse)(nil),         // 8: petstore.FindPetsByStatusResponse
	(*FindPetsByTagsRequest)(nil),            // 9: petstore.FindPetsByTagsRequest
	(*FindPetsByTagsResponse)(nil),           // 10: petstore.FindPetsByTagsResponse
	(*GetPetByIdRequest)(nil),                // 11: petstore.GetPetByIdRequest
	(*Order)(nil),                            // 12: petstore.Order
	(*DeleteOrderRequest)(nil),               // 13: petstore.DeleteOrderRequest
	(*GetInventoryResponse)(nil),             // 14: petstore.GetInventoryResponse
	(*MapInventory)(nil),                     // 15: petstore.MapInventory
	(*GetOrderByIdRequest)(nil),              // 16: petstore.GetOrderByIdRequest
	(*PlaceOrderRequest)(nil),                // 17: petstore.PlaceOrderRequest
	(*Pet)(nil),                              // 18: petstore.Pet
	(*Tag)(nil),                              // 19: petstore.Tag
	(*UpdatePetRequest)(nil),                 // 20: petstore.UpdatePetRequest
	(*UpdatePetWithFormRequest)(nil),         // 21: petstore.UpdatePetWithFormRequest
	(*UploadFileRequest)(nil),                // 22: petstore.UploadFileRequest
	(*User)(nil),                             // 23: petstore.User
	(*CreateUserRequest)(nil),                // 24: petstore.CreateUserRequest
	(*CreateUsersWithArrayInputRequest)(nil), // 25: petstore.CreateUsersWithArrayInputRequest
	(*CreateUsersWithListInputRequest)(nil),  // 26: petstore.CreateUsersWithListInputRequest
	(*DeleteUserRequest)(nil),                // 27: petstore.DeleteUserRequest
	(*GetUserByNameRequest)(nil),             // 28: petstore.GetUserByNameRequest
	(*LoginUserRequest)(nil),                 // 29: petstore.LoginUserRequest
	(*UpdateUserRequest)(nil),                // 30: petstore.UpdateUserRequest
	(*empty.Empty)(nil),                      // 31: google.protobuf.Empty
}
var file_protobuffer_swaggerpetstore_petstore_proto_depIdxs = []int32{
	18, // 0: petstore.AddPetRequest.body:type_name -> petstore.Pet
	0,  // 1: petstore.FindPetsByStatusRequest.status:type_name -> petstore.FindPetsByStatusRequest.Status
	18, // 2: petstore.FindPetsByStatusResponse.items:type_name -> petstore.Pet
	18, // 3: petstore.FindPetsByTagsResponse.items:type_name -> petstore.Pet
	1,  // 4: petstore.Order.status:type_name -> petstore.Order.OrderStatus
	15, // 5: petstore.GetInventoryResponse.items:type_name -> petstore.MapInventory
	12, // 6: petstore.PlaceOrderRequest.body:type_name -> petstore.Order
	5,  // 7: petstore.Pet.category:type_name -> petstore.Category
	2,  // 8: petstore.Pet.status:type_name -> petstore.Pet.PetStatus
	19, // 9: petstore.Pet.tags:type_name -> petstore.Tag
	18, // 10: petstore.UpdatePetRequest.body:type_name -> petstore.Pet
	23, // 11: petstore.CreateUserRequest.body:type_name -> petstore.User
	23, // 12: petstore.CreateUsersWithArrayInputRequest.body:type_name -> petstore.User
	23, // 13: petstore.CreateUsersWithListInputRequest.body:type_name -> petstore.User
	23, // 14: petstore.UpdateUserRequest.body:type_name -> petstore.User
	3,  // 15: petstore.SwaggerPetstoreService.AddPet:input_type -> petstore.AddPetRequest
	13, // 16: petstore.SwaggerPetstoreService.DeleteOrder:input_type -> petstore.DeleteOrderRequest
	6,  // 17: petstore.SwaggerPetstoreService.DeletePet:input_type -> petstore.DeletePetRequest
	7,  // 18: petstore.SwaggerPetstoreService.FindPetsByStatus:input_type -> petstore.FindPetsByStatusRequest
	9,  // 19: petstore.SwaggerPetstoreService.FindPetsByTags:input_type -> petstore.FindPetsByTagsRequest
	31, // 20: petstore.SwaggerPetstoreService.GetInventory:input_type -> google.protobuf.Empty
	16, // 21: petstore.SwaggerPetstoreService.GetOrderById:input_type -> petstore.GetOrderByIdRequest
	11, // 22: petstore.SwaggerPetstoreService.GetPetById:input_type -> petstore.GetPetByIdRequest
	20, // 23: petstore.SwaggerPetstoreService.UpdatePet:input_type -> petstore.UpdatePetRequest
	21, // 24: petstore.SwaggerPetstoreService.UpdatePetWithForm:input_type -> petstore.UpdatePetWithFormRequest
	22, // 25: petstore.SwaggerPetstoreService.UploadFile:input_type -> petstore.UploadFileRequest
	24, // 26: petstore.SwaggerPetstoreService.CreateUser:input_type -> petstore.CreateUserRequest
	25, // 27: petstore.SwaggerPetstoreService.CreateUsersWithArrayInput:input_type -> petstore.CreateUsersWithArrayInputRequest
	26, // 28: petstore.SwaggerPetstoreService.CreateUsersWithListInput:input_type -> petstore.CreateUsersWithListInputRequest
	27, // 29: petstore.SwaggerPetstoreService.DeleteUser:input_type -> petstore.DeleteUserRequest
	28, // 30: petstore.SwaggerPetstoreService.GetUserByName:input_type -> petstore.GetUserByNameRequest
	29, // 31: petstore.SwaggerPetstoreService.LoginUser:input_type -> petstore.LoginUserRequest
	31, // 32: petstore.SwaggerPetstoreService.LogoutUser:input_type -> google.protobuf.Empty
	17, // 33: petstore.SwaggerPetstoreService.PlaceOrder:input_type -> petstore.PlaceOrderRequest
	30, // 34: petstore.SwaggerPetstoreService.UpdateUser:input_type -> petstore.UpdateUserRequest
	31, // 35: petstore.SwaggerPetstoreService.AddPet:output_type -> google.protobuf.Empty
	31, // 36: petstore.SwaggerPetstoreService.DeleteOrder:output_type -> google.protobuf.Empty
	31, // 37: petstore.SwaggerPetstoreService.DeletePet:output_type -> google.protobuf.Empty
	8,  // 38: petstore.SwaggerPetstoreService.FindPetsByStatus:output_type -> petstore.FindPetsByStatusResponse
	10, // 39: petstore.SwaggerPetstoreService.FindPetsByTags:output_type -> petstore.FindPetsByTagsResponse
	14, // 40: petstore.SwaggerPetstoreService.GetInventory:output_type -> petstore.GetInventoryResponse
	12, // 41: petstore.SwaggerPetstoreService.GetOrderById:output_type -> petstore.Order
	18, // 42: petstore.SwaggerPetstoreService.GetPetById:output_type -> petstore.Pet
	31, // 43: petstore.SwaggerPetstoreService.UpdatePet:output_type -> google.protobuf.Empty
	31, // 44: petstore.SwaggerPetstoreService.UpdatePetWithForm:output_type -> google.protobuf.Empty
	4,  // 45: petstore.SwaggerPetstoreService.UploadFile:output_type -> petstore.ApiResponse
	31, // 46: petstore.SwaggerPetstoreService.CreateUser:output_type -> google.protobuf.Empty
	31, // 47: petstore.SwaggerPetstoreService.CreateUsersWithArrayInput:output_type -> google.protobuf.Empty
	31, // 48: petstore.SwaggerPetstoreService.CreateUsersWithListInput:output_type -> google.protobuf.Empty
	31, // 49: petstore.SwaggerPetstoreService.DeleteUser:output_type -> google.protobuf.Empty
	23, // 50: petstore.SwaggerPetstoreService.GetUserByName:output_type -> petstore.User
	4,  // 51: petstore.SwaggerPetstoreService.LoginUser:output_type -> petstore.ApiResponse
	31, // 52: petstore.SwaggerPetstoreService.LogoutUser:output_type -> google.protobuf.Empty
	12, // 53: petstore.SwaggerPetstoreService.PlaceOrder:output_type -> petstore.Order
	31, // 54: petstore.SwaggerPetstoreService.UpdateUser:output_type -> google.protobuf.Empty
	35, // [35:55] is the sub-list for method output_type
	15, // [15:35] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_protobuffer_swaggerpetstore_petstore_proto_init() }
func file_protobuffer_swaggerpetstore_petstore_proto_init() {
	if File_protobuffer_swaggerpetstore_petstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuffer_swaggerpetstore_petstore_proto_rawDesc), len(file_protobuffer_swaggerpetstore_petstore_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuffer_swaggerpetstore_petstore_proto_goTypes,
		DependencyIndexes: file_protobuffer_swaggerpetstore_petstore_proto_depIdxs,
		EnumInfos:         file_protobuffer_swaggerpetstore_petstore_proto_enumTypes,
		MessageInfos:      file_protobuffer_swaggerpetstore_petstore_proto_msgTypes,
	}.Build()
	File_protobuffer_swaggerpetstore_petstore_proto = out.File
	file_protobuffer_swaggerpetstore_petstore_proto_goTypes = nil
	file_protobuffer_swaggerpetstore_petstore_proto_depIdxs = nil
}
