// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: protobuffer/swaggerpetstore/petstore.proto

package petstore

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwaggerPetstoreService_AddPet_FullMethodName                    = "/petstore.SwaggerPetstoreService/AddPet"
	SwaggerPetstoreService_DeleteOrder_FullMethodName               = "/petstore.SwaggerPetstoreService/DeleteOrder"
	SwaggerPetstoreService_DeletePet_FullMethodName                 = "/petstore.SwaggerPetstoreService/DeletePet"
	SwaggerPetstoreService_FindPetsByStatus_FullMethodName          = "/petstore.SwaggerPetstoreService/FindPetsByStatus"
	SwaggerPetstoreService_FindPetsByTags_FullMethodName            = "/petstore.SwaggerPetstoreService/FindPetsByTags"
	SwaggerPetstoreService_GetInventory_FullMethodName              = "/petstore.SwaggerPetstoreService/GetInventory"
	SwaggerPetstoreService_GetOrderById_FullMethodName              = "/petstore.SwaggerPetstoreService/GetOrderById"
	SwaggerPetstoreService_GetPetById_FullMethodName                = "/petstore.SwaggerPetstoreService/GetPetById"
	SwaggerPetstoreService_UpdatePet_FullMethodName                 = "/petstore.SwaggerPetstoreService/UpdatePet"
	SwaggerPetstoreService_UpdatePetWithForm_FullMethodName         = "/petstore.SwaggerPetstoreService/UpdatePetWithForm"
	SwaggerPetstoreService_UploadFile_FullMethodName                = "/petstore.SwaggerPetstoreService/UploadFile"
	SwaggerPetstoreService_CreateUser_FullMethodName                = "/petstore.SwaggerPetstoreService/CreateUser"
	SwaggerPetstoreService_CreateUsersWithArrayInput_FullMethodName = "/petstore.SwaggerPetstoreService/CreateUsersWithArrayInput"
	SwaggerPetstoreService_CreateUsersWithListInput_FullMethodName  = "/petstore.SwaggerPetstoreService/CreateUsersWithListInput"
	SwaggerPetstoreService_DeleteUser_FullMethodName                = "/petstore.SwaggerPetstoreService/DeleteUser"
	SwaggerPetstoreService_GetUserByName_FullMethodName             = "/petstore.SwaggerPetstoreService/GetUserByName"
	SwaggerPetstoreService_LoginUser_FullMethodName                 = "/petstore.SwaggerPetstoreService/LoginUser"
	SwaggerPetstoreService_LogoutUser_FullMethodName                = "/petstore.SwaggerPetstoreService/LogoutUser"
	SwaggerPetstoreService_PlaceOrder_FullMethodName                = "/petstore.SwaggerPetstoreService/PlaceOrder"
	SwaggerPetstoreService_UpdateUser_FullMethodName                = "/petstore.SwaggerPetstoreService/UpdateUser"
)

// SwaggerPetstoreServiceClient is the client API for SwaggerPetstoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwaggerPetstoreServiceClient interface {
	// Add a new pet to the store
	AddPet(ctx context.Context, in *AddPetRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete purchase order by ID
	//
	// For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
	DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Deletes a pet
	DeletePet(ctx context.Context, in *DeletePetRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Finds Pets by status
	//
	// Multiple status values can be provided with comma separated strings
	FindPetsByStatus(ctx context.Context, in *FindPetsByStatusRequest, opts ...grpc.CallOption) (*FindPetsByStatusResponse, error)
	// Finds Pets by tags
	//
	// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
	FindPetsByTags(ctx context.Context, in *FindPetsByTagsRequest, opts ...grpc.CallOption) (*FindPetsByTagsResponse, error)
	// Returns pet inventories by status
	//
	// Returns a map of status codes to quantities
	GetInventory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	// Find purchase order by ID
	//
	// For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
	GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*Order, error)
	// Find pet by ID
	//
	// Returns a single pet
	GetPetById(ctx context.Context, in *GetPetByIdRequest, opts ...grpc.CallOption) (*Pet, error)
	// Update an existing pet
	UpdatePet(ctx context.Context, in *UpdatePetRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Updates a pet in the store with form data
	UpdatePetWithForm(ctx context.Context, in *UpdatePetWithFormRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// uploads an image
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	// Create user
	//
	// This can only be done by the logged in user.
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Creates list of users with given input array
	CreateUsersWithArrayInput(ctx context.Context, in *CreateUsersWithArrayInputRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Creates list of users with given input array
	CreateUsersWithListInput(ctx context.Context, in *CreateUsersWithListInputRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete user
	//
	// This can only be done by the logged in user.
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get user by user name
	GetUserByName(ctx context.Context, in *GetUserByNameRequest, opts ...grpc.CallOption) (*User, error)
	// Logs user into the system
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	// Logs out current logged in user session
	LogoutUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Place an order for a pet
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*Order, error)
	// Updated user
	//
	// This can only be done by the logged in user.
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type swaggerPetstoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwaggerPetstoreServiceClient(cc grpc.ClientConnInterface) SwaggerPetstoreServiceClient {
	return &swaggerPetstoreServiceClient{cc}
}

func (c *swaggerPetstoreServiceClient) AddPet(ctx context.Context, in *AddPetRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_AddPet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_DeleteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) DeletePet(ctx context.Context, in *DeletePetRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_DeletePet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) FindPetsByStatus(ctx context.Context, in *FindPetsByStatusRequest, opts ...grpc.CallOption) (*FindPetsByStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindPetsByStatusResponse)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_FindPetsByStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) FindPetsByTags(ctx context.Context, in *FindPetsByTagsRequest, opts ...grpc.CallOption) (*FindPetsByTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindPetsByTagsResponse)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_FindPetsByTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) GetInventory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_GetOrderById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) GetPetById(ctx context.Context, in *GetPetByIdRequest, opts ...grpc.CallOption) (*Pet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pet)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_GetPetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) UpdatePet(ctx context.Context, in *UpdatePetRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_UpdatePet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) UpdatePetWithForm(ctx context.Context, in *UpdatePetWithFormRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_UpdatePetWithForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) CreateUsersWithArrayInput(ctx context.Context, in *CreateUsersWithArrayInputRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_CreateUsersWithArrayInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) CreateUsersWithListInput(ctx context.Context, in *CreateUsersWithListInputRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_CreateUsersWithListInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) GetUserByName(ctx context.Context, in *GetUserByNameRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_GetUserByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) LogoutUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_LogoutUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerPetstoreServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SwaggerPetstoreService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwaggerPetstoreServiceServer is the server API for SwaggerPetstoreService service.
// All implementations must embed UnimplementedSwaggerPetstoreServiceServer
// for forward compatibility.
type SwaggerPetstoreServiceServer interface {
	// Add a new pet to the store
	AddPet(context.Context, *AddPetRequest) (*empty.Empty, error)
	// Delete purchase order by ID
	//
	// For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
	DeleteOrder(context.Context, *DeleteOrderRequest) (*empty.Empty, error)
	// Deletes a pet
	DeletePet(context.Context, *DeletePetRequest) (*empty.Empty, error)
	// Finds Pets by status
	//
	// Multiple status values can be provided with comma separated strings
	FindPetsByStatus(context.Context, *FindPetsByStatusRequest) (*FindPetsByStatusResponse, error)
	// Finds Pets by tags
	//
	// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
	FindPetsByTags(context.Context, *FindPetsByTagsRequest) (*FindPetsByTagsResponse, error)
	// Returns pet inventories by status
	//
	// Returns a map of status codes to quantities
	GetInventory(context.Context, *empty.Empty) (*GetInventoryResponse, error)
	// Find purchase order by ID
	//
	// For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
	GetOrderById(context.Context, *GetOrderByIdRequest) (*Order, error)
	// Find pet by ID
	//
	// Returns a single pet
	GetPetById(context.Context, *GetPetByIdRequest) (*Pet, error)
	// Update an existing pet
	UpdatePet(context.Context, *UpdatePetRequest) (*empty.Empty, error)
	// Updates a pet in the store with form data
	UpdatePetWithForm(context.Context, *UpdatePetWithFormRequest) (*empty.Empty, error)
	// uploads an image
	UploadFile(context.Context, *UploadFileRequest) (*ApiResponse, error)
	// Create user
	//
	// This can only be done by the logged in user.
	CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
	// Creates list of users with given input array
	CreateUsersWithArrayInput(context.Context, *CreateUsersWithArrayInputRequest) (*empty.Empty, error)
	// Creates list of users with given input array
	CreateUsersWithListInput(context.Context, *CreateUsersWithListInputRequest) (*empty.Empty, error)
	// Delete user
	//
	// This can only be done by the logged in user.
	DeleteUser(context.Context, *DeleteUserRequest) (*empty.Empty, error)
	// Get user by user name
	GetUserByName(context.Context, *GetUserByNameRequest) (*User, error)
	// Logs user into the system
	LoginUser(context.Context, *LoginUserRequest) (*ApiResponse, error)
	// Logs out current logged in user session
	LogoutUser(context.Context, *empty.Empty) (*empty.Empty, error)
	// Place an order for a pet
	PlaceOrder(context.Context, *PlaceOrderRequest) (*Order, error)
	// Updated user
	//
	// This can only be done by the logged in user.
	UpdateUser(context.Context, *UpdateUserRequest) (*empty.Empty, error)
	mustEmbedUnimplementedSwaggerPetstoreServiceServer()
}

// UnimplementedSwaggerPetstoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwaggerPetstoreServiceServer struct{}

func (UnimplementedSwaggerPetstoreServiceServer) AddPet(context.Context, *AddPetRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPet not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) DeleteOrder(context.Context, *DeleteOrderRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrder not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) DeletePet(context.Context, *DeletePetRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePet not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) FindPetsByStatus(context.Context, *FindPetsByStatusRequest) (*FindPetsByStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPetsByStatus not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) FindPetsByTags(context.Context, *FindPetsByTagsRequest) (*FindPetsByTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPetsByTags not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) GetInventory(context.Context, *empty.Empty) (*GetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) GetOrderById(context.Context, *GetOrderByIdRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderById not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) GetPetById(context.Context, *GetPetByIdRequest) (*Pet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPetById not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) UpdatePet(context.Context, *UpdatePetRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePet not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) UpdatePetWithForm(context.Context, *UpdatePetWithFormRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePetWithForm not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) UploadFile(context.Context, *UploadFileRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) CreateUsersWithArrayInput(context.Context, *CreateUsersWithArrayInputRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUsersWithArrayInput not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) CreateUsersWithListInput(context.Context, *CreateUsersWithListInputRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUsersWithListInput not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) GetUserByName(context.Context, *GetUserByNameRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByName not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) LoginUser(context.Context, *LoginUserRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) LogoutUser(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutUser not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedSwaggerPetstoreServiceServer) mustEmbedUnimplementedSwaggerPetstoreServiceServer() {
}
func (UnimplementedSwaggerPetstoreServiceServer) testEmbeddedByValue() {}

// UnsafeSwaggerPetstoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwaggerPetstoreServiceServer will
// result in compilation errors.
type UnsafeSwaggerPetstoreServiceServer interface {
	mustEmbedUnimplementedSwaggerPetstoreServiceServer()
}

func RegisterSwaggerPetstoreServiceServer(s grpc.ServiceRegistrar, srv SwaggerPetstoreServiceServer) {
	// If the following call panics, it indicates UnimplementedSwaggerPetstoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwaggerPetstoreService_ServiceDesc, srv)
}

func _SwaggerPetstoreService_AddPet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).AddPet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_AddPet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).AddPet(ctx, req.(*AddPetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_DeleteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).DeleteOrder(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_DeletePet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).DeletePet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_DeletePet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).DeletePet(ctx, req.(*DeletePetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_FindPetsByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPetsByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).FindPetsByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_FindPetsByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).FindPetsByStatus(ctx, req.(*FindPetsByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_FindPetsByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPetsByTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).FindPetsByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_FindPetsByTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).FindPetsByTags(ctx, req.(*FindPetsByTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).GetInventory(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_GetOrderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).GetOrderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_GetOrderById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).GetOrderById(ctx, req.(*GetOrderByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_GetPetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).GetPetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_GetPetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).GetPetById(ctx, req.(*GetPetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_UpdatePet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).UpdatePet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_UpdatePet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).UpdatePet(ctx, req.(*UpdatePetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_UpdatePetWithForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePetWithFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).UpdatePetWithForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_UpdatePetWithForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).UpdatePetWithForm(ctx, req.(*UpdatePetWithFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_CreateUsersWithArrayInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUsersWithArrayInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).CreateUsersWithArrayInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_CreateUsersWithArrayInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).CreateUsersWithArrayInput(ctx, req.(*CreateUsersWithArrayInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_CreateUsersWithListInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUsersWithListInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).CreateUsersWithListInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_CreateUsersWithListInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).CreateUsersWithListInput(ctx, req.(*CreateUsersWithListInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_GetUserByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).GetUserByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_GetUserByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).GetUserByName(ctx, req.(*GetUserByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_LogoutUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).LogoutUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwaggerPetstoreService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerPetstoreServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwaggerPetstoreService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerPetstoreServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwaggerPetstoreService_ServiceDesc is the grpc.ServiceDesc for SwaggerPetstoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwaggerPetstoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "petstore.SwaggerPetstoreService",
	HandlerType: (*SwaggerPetstoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPet",
			Handler:    _SwaggerPetstoreService_AddPet_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _SwaggerPetstoreService_DeleteOrder_Handler,
		},
		{
			MethodName: "DeletePet",
			Handler:    _SwaggerPetstoreService_DeletePet_Handler,
		},
		{
			MethodName: "FindPetsByStatus",
			Handler:    _SwaggerPetstoreService_FindPetsByStatus_Handler,
		},
		{
			MethodName: "FindPetsByTags",
			Handler:    _SwaggerPetstoreService_FindPetsByTags_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _SwaggerPetstoreService_GetInventory_Handler,
		},
		{
			MethodName: "GetOrderById",
			Handler:    _SwaggerPetstoreService_GetOrderById_Handler,
		},
		{
			MethodName: "GetPetById",
			Handler:    _SwaggerPetstoreService_GetPetById_Handler,
		},
		{
			MethodName: "UpdatePet",
			Handler:    _SwaggerPetstoreService_UpdatePet_Handler,
		},
		{
			MethodName: "UpdatePetWithForm",
			Handler:    _SwaggerPetstoreService_UpdatePetWithForm_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _SwaggerPetstoreService_UploadFile_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _SwaggerPetstoreService_CreateUser_Handler,
		},
		{
			MethodName: "CreateUsersWithArrayInput",
			Handler:    _SwaggerPetstoreService_CreateUsersWithArrayInput_Handler,
		},
		{
			MethodName: "CreateUsersWithListInput",
			Handler:    _SwaggerPetstoreService_CreateUsersWithListInput_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _SwaggerPetstoreService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUserByName",
			Handler:    _SwaggerPetstoreService_GetUserByName_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _SwaggerPetstoreService_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _SwaggerPetstoreService_LogoutUser_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _SwaggerPetstoreService_PlaceOrder_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _SwaggerPetstoreService_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuffer/swaggerpetstore/petstore.proto",
}
