/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

// createUserEntity converts User DTO (protobuf) to UserEntity (MongoDB)
func createUserEntity(in *User) *UserEntity {
	if in == nil {
		return nil
	}
	return &UserEntity{
		Id:         in.Id,
		Username:   in.Username,
		FirstName:  in.FirstName,
		LastName:   in.LastName,
		Email:      in.Email,
		Password:   in.Password,
		Phone:      in.Phone,
		UserStatus: in.UserStatus,
	}
}

// createUserDTO converts UserEntity (MongoDB) to User DTO (protobuf)
func createUserDTO(in *UserEntity) *User {
	if in == nil {
		return nil
	}
	return &User{
		Id:         in.Id,
		Username:   in.Username,
		FirstName:  in.FirstName,
		LastName:   in.LastName,
		Email:      in.Email,
		Password:   in.Password,
		Phone:      in.Phone,
		UserStatus: in.UserStatus,
	}
}

// CreateUserListDTO converts a list of UserEntities to a list of User DTOs
func CreateUserListDTO(users []UserEntity) []*User {
	result := make([]*User, 0, len(users))
	for i := range users {
		result = append(result, createUserDTO(&users[i]))
	}
	return result
}
